### ISSUE TITLE
EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

### ISSUE THREAD

**Issue by SamDecrock** [shuoli84/SocketIOCocoa#11]
I'm getting

```
EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
```

I know it doesn't mean much, so here's a screenshot
![screen shot 2015-01-13 at 22 16 41](https://cloud.githubusercontent.com/assets/550487/5729371/2de8bf4a-9b72-11e4-8d69-ab7ff8275918.png)

located in EngineParser.swift

I'm using Xcode 6.1.1

**Comment by shuoli84** [comment]
Could be a bug in decoding payload, I'll check it.

发自我的 iPhone

**Comment by shuoli84** [comment]
@SamDecrock  which version of socketio server you are using?

**Comment by SamDecrock** [comment]
I'm using socketio 1.2.1 but I just tried it with 1.0.0 and I get the same error.

In my Node.js log I get the following incomming request:
```js
GET /?t=1421345585&EIO=3&transport=polling 200 15.470 ms - 489
````

It seems to be using polling. Can I force it to use websockets?

**Comment by SamDecrock** [comment]
Here's a screenshot with more debugging data:
![screen shot 2015-01-15 at 19 16 06](https://cloud.githubusercontent.com/assets/550487/5763492/0a24c804-9ceb-11e4-8407-ef4651ff46b1.png)

**Comment by shuoli84** [comment]
Sorry for the late reply, I just double checked your reply, you should set host to localhost/socket.io instead of localhost. 
But anyway, the crash should be fixed.

**Comment by iOSlong** [comment]
I get this crash error to ,

this is my codes: (referenced  in one roop !)
dispatch_async(recommend_report_queue(), ^{
        [[DQStatHelper sharedInstance] showAt:post withCurUrl:page];
    });
and then I change the thead method to 💯 
 dispatch_sync(recommend_report_queue(), ^{
        [[DQStatHelper sharedInstance] showAt:post withCurUrl:page];
    });

and  then ,  crash disappear .  maybe fix it by conincident.

i know it's about thread  , bug i don't know why.

**Comment by Nagesh8831** [comment]
![screen shot 2017-05-31 at 4 40 15 pm](https://cloud.githubusercontent.com/assets/28894364/26629836/c6274298-4621-11e7-8129-5b72be605733.png)

giving the thread error

**Comment by Nagesh8831** [comment]
please help to solve this problme
