### ISSUE TITLE
join/emit to rooms?

### ISSUE THREAD

**Issue by longbowww** [shuoli84/SocketIOCocoa#12]
is there a possibility to join rooms or to send messages/events to rooms? your documentation only says namespaces

€dit:
additionally how do you correctly utilize the protocol to open a socket in main viewcontroller and catch events on a second view controller without opening another socket/client?

**Comment by shuoli84** [comment]
Room support is implemented in server side, refer to http://socket.io/docs/server-api/. You can create a message like "join" and in the message handler in server, join the socket to a room. 

Per the second question: I use a singleton wrapper.
